<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-C379US1T" ignored="0" name="Test" tests="3" failures="1" timestamp="04 Feb 2025 15:20:22 GMT" time="50.43" errors="0">
  <testcase name="test_scenario1" time="2.653" classname="com.pdea.PlaywrightAutomation.PlaywrightAutomation"/>
  <testcase name="test_scenario2" time="4.806" classname="com.pdea.PlaywrightAutomation.PlaywrightAutomation"/>
  <testcase name="test_scenario3" time="7.296" classname="com.pdea.PlaywrightAutomation.PlaywrightAutomation">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Error message not as expected expected [Please fill out this field.] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error message not as expected expected [Please fill out this field.] but found [null]
at com.pdea.PlaywrightAutomation.PlaywrightAutomation.test_scenario3(PlaywrightAutomation.java:146)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- test_scenario3 -->
</testsuite> <!-- Test -->
